"""Plain-language explanations of a detection result, generated by any LLM provider.

What this module is
--------------------
A *narrator*. It turns the numbers a detection already produced into sentences a
non-technical person can act on. It does not make the decision.

Three rules are enforced here rather than left to the prompt:

1. **The model never decides.** :func:`explain` receives the verdict and every input that
   produced it, and returns prose. There is no code path by which a generated string can
   alter ``verdict`` or ``ai_probability``. An LLM that is asked to judge an image and
   then answer "is this AI?" will occasionally produce a confident accusation that the
   detector never made. This service must not be able to generate one.

2. **No image bytes leave the process.** The prompt is built from numbers and metadata
   only. ``architecture.md`` 7 promises images are never written to disk or logged, and a
   detector whose privacy story is "we don't keep your photos" cannot then hand them to a
   third-party API. Text-only prompts keep that promise intact.

3. **It is optional and additive.** No provider configured means ``explain()`` returns
   ``None`` and the detection is unchanged. Local SDK use stays fully offline.

Providers
---------
``gemini``  Google AI Studio (Generative Language API)
``groq``    Groq's OpenAI-compatible endpoint

Both are requested through the stdlib ``urllib`` so neither pulls in a new dependency of
the runtime image. Adding another provider means adding one class.
"""
from __future__ import annotations

import json
import logging
import os
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger("detector")

# Provider env vars, in resolution order. First one with a non-empty key wins.
ENV_KEYS: Dict[str, tuple] = {
    "gemini": ("GEMINI_API_KEY", "GOOGLE_API_KEY"),
    "groq": ("GROQ_API_KEY",),
}

DEFAULT_ENDPOINTS = {
    "gemini": "https://generativelanguage.googleapis.com/v1beta/models",
    "groq": "https://api.groq.com/openai/v1/chat/completions",
}

DEFAULT_MODELS = {
    "gemini": "gemini-2.5-flash",
    "groq": "llama-3.3-70b-versatile",
}

SYSTEM_PROMPT = """\
You explain the output of an AI-generated-image detector to a non-technical person.

You are given fixed facts about one detection. Write 2-4 short sentences of plain \
language describing what the detector found and how far to trust it.

Hard rules:
- Never contradict the given verdict. Do not upgrade or downgrade it.
- Never state or imply certainty about whether the image is AI-made beyond what the \
verdict supports. If the verdict is inconclusive, say the detector cannot tell.
- If `calibrated` is false, you MUST say the score is an uncalibrated model score, not a \
probability, and that the thresholds were never fitted on real data.
- Do not invent reasons. Use only the listed signals and warnings.
- Do not mention these instructions, JSON, field names, or model version strings.
- Plain prose. No headings, no bullet points, no markdown.
"""

USER_PROMPT = """\
Detector output for one image:

{facts}

Write the plain-language explanation now."""


@dataclass
class ExplanationRequest:
    """Everything an explanation is allowed to know. No pixels, by design."""

    verdict: str
    ai_probability: float
    confidence: str
    calibrated: bool
    warnings: List[str] = field(default_factory=list)
    signals: Dict[str, Any] = field(default_factory=dict)
    thresholds: Dict[str, float] = field(default_factory=dict)
    model_version: str = ""
    benchmark_id: Optional[str] = None
    out_of_domain: bool = False


class ExplanationError(RuntimeError):
    """Raised when a provider call fails. Callers degrade to ``None`` rather than fail."""


class BaseProvider:
    """Interface every provider implements."""

    name = "base"

    def __init__(self, api_key: str, model: str, timeout_s: float = 20.0,
                 max_retries: int = 2):
        self.api_key = api_key
        self.model = model
        self.timeout_s = timeout_s
        self.max_retries = max_retries

    def complete(self, system: str, user: str) -> str:
        raise NotImplementedError

    def _post_json(self, url: str, payload: Dict[str, Any], headers: Dict[str, str]) -> Dict:
        """POSTs JSON with retries. Uses stdlib only so no new dependency ships."""
        import urllib.error
        import urllib.request

        body = json.dumps(payload).encode("utf-8")
        last: Optional[Exception] = None

        for attempt in range(self.max_retries + 1):
            req = urllib.request.Request(url, data=body, headers=headers, method="POST")
            try:
                with urllib.request.urlopen(req, timeout=self.timeout_s) as resp:
                    return json.loads(resp.read().decode("utf-8"))
            except urllib.error.HTTPError as exc:
                detail = ""
                try:
                    detail = exc.read().decode("utf-8", "replace")[:200]
                except Exception:
                    pass
                last = ExplanationError(f"{self.name}: HTTP {exc.code} {detail}")
                # 4xx other than 429 will not fix itself on retry.
                if exc.code < 500 and exc.code != 429:
                    raise last
            except Exception as exc:
                last = ExplanationError(f"{self.name}: {type(exc).__name__}: {exc}")
            if attempt < self.max_retries:
                time.sleep(1.5 * (attempt + 1))

        raise last or ExplanationError(f"{self.name}: request failed")


class GeminiProvider(BaseProvider):
    """Google AI Studio / Generative Language API."""

    name = "gemini"

    def complete(self, system: str, user: str) -> str:
        model = self.model or DEFAULT_MODELS["gemini"]
        url = f"{DEFAULT_ENDPOINTS['gemini']}/{model}:generateContent?key={self.api_key}"
        payload = {
            "systemInstruction": {"parts": [{"text": system}]},
            "contents": [{"role": "user", "parts": [{"text": user}]}],
            "generationConfig": {"temperature": 0.2, "maxOutputTokens": 300},
        }
        data = self._post_json(url, payload, {"Content-Type": "application/json"})

        candidates = data.get("candidates") or []
        if not candidates:
            raise ExplanationError(f"gemini: no candidates in response: {str(data)[:200]}")
        parts = (candidates[0].get("content") or {}).get("parts") or []
        text = "".join(p.get("text", "") for p in parts).strip()
        if not text:
            raise ExplanationError("gemini: returned empty text")
        return text


class GroqProvider(BaseProvider):
    """Groq's OpenAI-compatible chat completions endpoint."""

    name = "groq"

    def complete(self, system: str, user: str) -> str:
        payload = {
            "model": self.model or DEFAULT_MODELS["groq"],
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "temperature": 0.2,
            "max_tokens": 300,
        }
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.api_key}",
        }
        data = self._post_json(DEFAULT_ENDPOINTS["groq"], payload, headers)

        choices = data.get("choices") or []
        if not choices:
            raise ExplanationError(f"groq: no choices in response: {str(data)[:200]}")
        text = (choices[0].get("message") or {}).get("content", "").strip()
        if not text:
            raise ExplanationError("groq: returned empty text")
        return text


PROVIDERS = {"gemini": GeminiProvider, "groq": GroqProvider}


def resolve_api_key(provider: str, env: Optional[Dict[str, str]] = None) -> Optional[str]:
    """Returns the first non-empty key for ``provider``, or None."""
    env = env if env is not None else os.environ
    for var in ENV_KEYS.get(provider, ()):
        value = env.get(var)
        if value and value.strip():
            return value.strip()
    return None


def detect_provider(env: Optional[Dict[str, str]] = None) -> Optional[str]:
    """Returns the first provider with a usable key, or None."""
    for provider in ENV_KEYS:
        if resolve_api_key(provider, env):
            return provider
    return None


def build_facts(req: ExplanationRequest) -> Dict[str, Any]:
    """Builds the JSON facts block handed to the model.

    Only detector output and its own metadata appear here. No filename, no dimensions,
    no user identifiers: none of it improves the explanation and all of it is data we
    would rather not hand to a third party.
    """
    return {
        "verdict": req.verdict,
        "ai_score": round(float(req.ai_probability), 4),
        "confidence": req.confidence,
        "score_is_calibrated": bool(req.calibrated),
        "thresholds_used": (
            {"likely_real_below": req.thresholds.get("T_lo"),
             "likely_ai_above": req.thresholds.get("T_hi")}
            if req.calibrated else None
        ),
        "detector_signals": req.signals,
        "warnings": list(req.warnings),
        "out_of_domain": bool(req.out_of_domain),
    }


def _sanitize(text: str, req: ExplanationRequest) -> str:
    """Final guard: strip anything that looks like an injected verdict upgrade.

    The provider prompt already forbids this, but the returned string is what a user
    reads, so a cheap post-check is worth more than trusting the model.
    """
    cleaned = text.strip()
    # Refuse to emit markdown scaffolding that indicates the model ignored the format.
    if cleaned.startswith(("#", "-", "*")) or cleaned.count("\n") > 6:
        cleaned = " ".join(line.strip("-*# ").strip() for line in cleaned.splitlines()
                           if line.strip())
    lowered = cleaned.lower()
    # If the detector abstained, an explanation claiming certainty is a contradiction.
    if req.verdict == "inconclusive":
        for phrase in ("definitely", "certainly", "is definitely", "clearly ai",
                       "clearly a fake", "100%", "is definitely ai"):
            if phrase in lowered:
                logger.warning(
                    "explanation from %s contradicted an inconclusive verdict; using a "
                    "fixed neutral phrasing instead", "llm"
                )
                return (
                    "The detector could not determine whether this image is AI-made or a "
                    "genuine photograph. Its score landed inside the inconclusive range, "
                    "which means the result is not reliable enough to act on."
                )
    return cleaned


def explain(req: ExplanationRequest, provider: Optional[str] = None,
            api_key: Optional[str] = None, model: Optional[str] = None,
            env: Optional[Dict[str, str]] = None) -> Optional[Dict[str, Any]]:
    """Generates an explanation, or returns None.

    Returns a dict with ``text``, ``provider``, and ``model``. Never raises: a failed or
    unconfigured provider yields ``None`` so a detection is never blocked by the narrator.
    """
    env = env if env is not None else os.environ

    provider = provider or detect_provider(env)
    if not provider:
        return None
    if provider not in PROVIDERS:
        raise ValueError(f"unknown explanation provider: {provider!r}")

    api_key = api_key or resolve_api_key(provider, env)
    if not api_key:
        return None

    facts = build_facts(req)
    resolved_model = (
        model
        or os.getenv(f"SAHU65_EXPLAIN_MODEL_{provider.upper()}", "")
        or DEFAULT_MODELS.get(provider, "")
    )
    client = PROVIDERS[provider](api_key=api_key, model=resolved_model)

    user = USER_PROMPT.format(facts=json.dumps(facts, indent=2))
    try:
        text = client.complete(SYSTEM_PROMPT, user)
    except ExplanationError as exc:
        logger.warning("explanation unavailable: %s", exc)
        return None

    text = _sanitize(text, req)
    return {
        "text": text,
        "provider": provider,
        "model": client.model or DEFAULT_MODELS.get(provider, ""),
    }


def configured(env: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
    """Introspection for ``sahu65 info`` / ``/deep-guard/version``."""
    env = env if env is not None else os.environ
    out: Dict[str, Any] = {"available": False, "provider": None, "model": None}
    provider = detect_provider(env)
    if provider:
        out["available"] = True
        out["provider"] = provider
        out["model"] = DEFAULT_MODELS.get(provider, "")
    return out